version: '3'
services:
  db:
    build: ./docker/mysql
    restart: always
    volumes:
      - ./docker/mysql/persistence:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
    networks:
      - backend_internal
  api:
    image: alpine:latest
    restart: always
    entrypoint: "/go-bin/secret-form"
    volumes:
      - "./docker/server:/go-bin"
    environment:
      - FORMENVPATH=/go-bin/.env-dockerdev
    networks:
      - backend_internal
      - backend_proxy
  frontend:
    image: node:10.18
    restart: always
    entrypoint: "yarn --cwd /react-app start"
    volumes:
      - "./secret-form-client:/react-app"
    networks:
      - frontend_proxy
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - "./docker/nginx:/etc/nginx/conf.d:ro"
    ports:
      - "8000:80"
    networks:
      - backend_proxy
      - frontend_proxy
networks:
  backend_internal:
    driver: bridge
  frontend_proxy:
    driver: bridge
  backend_proxy:
    driver: bridge
